config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	
	root to:"board#index"

	#Board
	delete '/board/:id', to: 'board#delete', as: :delete_board

	get "/boards", to: "board#index", as: :index_board

	get '/board/:id', to: 'board#show', as: :show_board

	get '/boardinfo/:id', to: 'board#get', as: :get_board

	post '/boards', to: "board#create"

	patch '/boardseditname/:id', to: "board#edit", as: :board_edit_name

	#Column
	delete '/columns/:id', to: 'column#delete', as: :delete_column

	post '/board/:id', to: "column#createtitle", as: :create_column

	get '/columns/:id', to: 'column#get', as: :get_column

	get '/columns/:id/show', to: 'column#show', as: :show_column
	
	patch '/columnseditname/:id', to: "column#edit", as: :column_edit_name

	patch '/columns/:id/move', to: "column#move"

	#Card
	delete '/card/:id', to: 'card#delete', as: :delete_card

	get '/column/:id', to: 'card#getcolumn', as: :get_column_card

	get '/card/:id', to: 'card#get', as: :get_card

	get '/cardmodal/:id', to: 'card#modalshow', as: :get_modalshow_card

	patch '/cardedit/:id', to: "card#edit", as: :edit_card

	patch '/columns/:column_id/cards/:id/move', to: "card#move"

	post "/cardcreate/:id", to: "card#create", as: :create_card

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
	has_many :columns
	validates :name, :presence => true, length: { minimum: 3 }
end

app/models/card.rb
class Card < ApplicationRecord
	acts_as_list
	belongs_to :column
	has_many :check_items
	validates :title, :presence => true
	validates :column_id, :presence => true
end

app/models/check_item.rb
class CheckItem < ApplicationRecord
	belongs_to :card
end

app/models/column.rb
class Column < ApplicationRecord
	acts_as_list
	belongs_to :board
	has_many :cards
	validates :name, :presence => true, length: { minimum: 3 }
	validates :board_id, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
 
 	respond_to :js
	helper_method :show_card

	def new
		@board = Board.find(params[:id])
	end

	def index
		@board = Board.new
		@boards = Board.all
		@columns = Column.all
		
		respond_to do |format|
			format.html { render 'index.html.erb' }
			format.js { render 'index.js.erb' }
      	end
	end

	def show
		@board = Board.find(params[:id])
		@columns = Column.where(:board_id => params[:id])
		render "board"
	end

	def show_card(column_id)
		@column = Column.find(column_id)
		@board = Board.find(params[:id])
		@cards = Card.where(:column_id => @column.id)

		return 'card/show'
	end

	def delete
		@board = Board.find(params[:id])
		@boards = Board.all()
		@columns = Column.where(:board_id => params[:id])
		if @board.destroy
			flash[:notice] = 'Board excluida!'
			redirect_to index_board_path()
		else
			render "board/index"
		end
	end

	def reload
		@columns = Column.where(:board_id => params[:id])
	end

	def create
		@board = Board.new(board_params)
		@boards = Board.all
		@columns = Column.all

		if @board.save
			flash[:notice] = 'Board criado com sucesso!'
			render "board/index"
		else
			flash[:notice] = 'Board não foi criada!'
			render "board/index"
		end
	end

	def get
		@board = Board.find(params[:id])

		render 'board/modaledit'
	end

	def edit
		@board = Board.find(params[:id])
		@board.name = params[:board][:name]
		@boards = Board.all
		@columns = Column.all

		if @board.save
			redirect_to show_board_path(@board.id), alert: "Board editada com sucesso!"
		else
			redirect_to show_board_path(@board.id), alert: "Board não foi editada com sucesso!"
		end
	end

	private

	def board_params
		params.require(:board).permit(:id, :name)
	end
end

app/controllers/card_controller.rb
class CardController < ApplicationController

	def index
  		@cards = Card.all
	end

	def getcolumn
		@column = Column.find(params[:id])

		render 'card/modal'
	end

	def get
		@card = Card.find(params[:id])

		render 'card/modaledit'
	end

	def modalshow
		@card = Card.find(params[:id])

		render 'card/modalshow'
	end

	def show
		@column = Column.find(params[:id])
		@cards = Card.where(:column_id => params[:id])

		render 'card/show'
	end

	def create
		@card = Card.new(card_params)
		@card.column_id = params[:id]
		@boards = Board.all
		@column = Column.find(params[:id])
		@board = Board.find(@column.board_id)
		@columns = Column.all

		if @card.save
			redirect_to show_board_path(@board.id), alert: "Card criado com sucesso!"
		else
			redirect_to show_board_path(@board.id), alert: "Card excluido sem sucesso!"
		end
	end

	def edit
		@card = Card.find(params[:id])
		@boards = Board.all
		@column = Column.find(@card.column_id)
		@columns = Column.where(:board_id => @column.board_id)
		@board = Board.find(@column.board_id)

		if @card.update(card_params)
			redirect_to show_board_path(@board.id), alert: "card editada com sucesso!"
		else
			redirect_to show_board_path(@board.id), alert: "card não foi editada com sucesso!"
		end
	end

	def delete
		@card = Card.find(params[:id])
		@column = Column.find(@card.column_id)
		@columns = Column.where(:board_id => @column.board_id)
		@board = Board.find(@column.board_id)
		
		if @card.destroy
			redirect_to show_board_path(@column.board_id), alert: "card excluido com sucesso!"
		else
			redirect_to show_board_path(@column.board_id), alert: "O card nao foi excluido."
		end
	end

	def move
		@card = Card.find(params[:id])
		@card.column_id = params[:column_id]
		@card.position = params[:position]
		@card.save
		head :ok
	end

	private 

	def card_params
		params.require(:card).permit(:id, :title, :description, :board_id, :position)
	end
end

app/controllers/column_controller.rb
class ColumnController < ApplicationController
	
	before_action :set_column, only: [:edit, :update]

	def index
		@columns = Columns.all
	end

	def delete
		@column = Column.find(params[:id])
		@columns = Column.where(:board_id => @column.board_id)
		@board = Board.find(@column.board_id)
		if @column.destroy
			redirect_to show_board_path(@column.board_id), alert: "Coluna excluido com sucesso!"
		else
			redirect_to show_board_path(@column.board_id), alert: "A coluna nao foi excluida."
		end
	end

	def get
		@column = Column.find(params[:id])

		render 'column/modal'
	end
	
	def createtitle
	  	@column = Column.new(column_params)
	  	@column.board_id = params[:id]
		@columns = Column.where(:board_id => @column.board_id)
		@boards = Board.all
		@board = Board.find(params[:id])
		@columns = Column.all

	  	if @column.save
	  		redirect_to show_board_path, alert: "Coluna criada com sucesso!"
	  	else
	  		redirect_to show_board_path, alert: "Coluna excluida sem sucesso!"
	  	end
	end

	def edit
		@boards = Board.all
		@columns = Column.all
		@board = Board.find(@column.board_id)

		if @column.update(name: params[:column][:name])
			redirect_to show_board_path(@board.id), alert: "Coluna editada com sucesso!"
		else
			redirect_to show_board_path(@board.id), alert: "Coluna não foi editada com sucesso!"
		end
	end

	def move
		@column = Column.find(params[:id])
		@column.insert_at(params[:position].to_i)
		head :ok
	end

	private

	def set_column
		@column = Column.find(params[:id])
	end

	def column_params
		params.require(:column).permit(:id, :name, :board_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/column_helper.rb
module ColumnHelper
end

app/views/board/_form.html.erb
<div class="form-inline">
	<%= simple_form_for Board.new, url: "/boards", wrapper: :inline_form do |form| %>
		<%= form.label :Nome %>
		<%= form.input_field :name %>
		<%= form.submit %>
	<% end %>
</div>

app/views/board/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Cadastrar Board</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       
		    <%= render 'board/form' %>
      </div>
    </div>
  </div>
</div>

app/views/board/_modaledit.html.erb
<div class="modal-dialog" role="document">
<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Editar Board</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
	    <div class="form-inline">
			<%= simple_form_for @board, url: board_edit_name_path(), wrapper: :inline_form do |form| %>
				<p>Nome: <%= form.input_field :name %> <%= form.submit "Salvar" %></p>
			<% end %>
		</div>
  </div>
</div>
</div>

app/views/board/board.html.erb
<div class="width: 100%;height:100%">
	<div class="inline margin5left" style="align-items: center;">
		<h2> Board: <%= @board.name %></h2> 
		<div style="margin-left: 30px;">
			<div class="inline alignright">
				<%= link_to "Editar", get_board_path(@board.id), :class => "btn", remote: true, "data-toggle" => "modal", 'data-target' => '#exampleModal2', 'data-id' => @board.id,
								:class => 'btn btn-info btn-sm margin5right' %>
		      	<div class="modal" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
		      	
				<%= button_to("Excluir", delete_board_path(@board), :method => :delete, :class => 'btn btn-info btn-sm') %>
			</div>
		</div>
	</div>
	<%= render 'column/form', board: @board %>
	<%= render 'column/show', columns: @columns %>
</div>

app/views/board/index.html.erb
<div class="card text-center center" style="width: 60%;margin: 0 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added">
  <div class="card-header">
    Boards
  </div>
  <div class="card-body">
    <div class="form-inline">
		<p>Selecione um Board
		<select class="selectpicker" title="Selecione" onchange="location = this.value;" data-none-selected-text="please select...">
			<option>Selecione</option>
			<% @boards.each do |board|%>
				<option value="<%= show_board_path(:id => board.id)%>"><%= board.name %></option>
			<% end %>
		</select>
		</p>
	</div>
	<p> Ou </p>
	<%= link_to "Criar um Board", "#", "data-toggle" => "modal", 'data-target' => '#exampleModal'  %>
	<%= render 'board/modal'%>
	</div>
	<div class="card-footer text-muted">
	<p><%= flash[:notice] %></p>
	<% if @board.errors.any? %>
	  <div id="error_explanation">
	   <div class="alert alert-error">
	     The form contains <%= pluralize(@board.errors.count, "error") %>.
	   </div>
	  <ul>
	   <% @board.errors.full_messages.each do |msg| %>
	    <li>* <%= msg %></li>
	   <% end %>
	 </ul>
	</div>
	<% end %>
	</div>
</div>

app/views/board/index.js.erb
//$("selectpicker").change(function(){
//	alert("The text has been changed.");
//	$('#column_list a').parent().html("<%= j render 'column/show', board: @board%>")
//});

app/views/board/modaledit.js.erb
$("#exampleModal2").html("<%= j render 'board/modaledit'%>");
$("#exampleModal2").show();

app/views/card/_modal.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Cadastrar Task</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
	    <div>
        <p class="teste"></p>
        <%= simple_form_for Card.new, url: create_card_path(), wrapper: :inline_form  do |form| %>
          <p>Criar nova Task: </p>
          <p><%= form.input_field :title %> </p>
          <p><%= form.input_field :description %> </p>
          <p><%= form.input_field :dateFinish %> </p>
          <p><%= form.submit "Salvar" %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/card/_modaledit.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Editar Task</h5>
      <%= button_to("Excluir", delete_card_path(@card), :method => :delete, :class => 'btn btn-info btn-sm margin5right') %>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
	    <div>
        <p class="teste"></p>
        <%= simple_form_for @card, url: edit_card_path(), wrapper: :inline_form  do |form| %>
          <p>Editar Task: </p>
          <p><%= form.label :Titulo %>
          <%= form.input_field :title %> </p>
          <p style="display: flex;"><%= form.label :descrição %>
          <%= form.input_field :description %> </p>
          <p><%= form.label :Data_Termino %>
          <%= form.input_field :dateFinish %> </p>
          <p><%= form.submit "Salvar" %></p>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/card/_modalshow.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Task</h5>
      <%= button_to("Excluir", delete_card_path(@card), :method => :delete, :class => 'btn btn-info btn-sm margin5right') %>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
	    <div>
			<p class="teste"></p>
			<p>Titulo: <%= @card.title %></p>
			<p>Descrição: <%= @card.description %> </p>
			<p>Data termino: <%= @card.dateFinish %> </p>
      </div>
    </div>
  </div>
</div>

app/views/card/_show.html.erb
<div data-controller="card" data-column="<%= columnid %>">
	<% cards.order(position: :asc).each do |card|%>
		<div class="card" style="margin-top:3px;" data-id="<%= card.id %>" data-id-column="<%= card.column_id %>" data-drag-url="/columns/:column_id/cards/:id/move">	
			<div class="card-body">
				<%= link_to get_modalshow_card_path(card.id), remote: true, "data-toggle" => "modal", 'data-target' => '#cardmodalshow', 'data-id' => card.id do %>
					<%= card.title %>
				<% end %>
				<div class="modal" id="cardmodalshow" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
				<div class="inline alignright test">
					<%= link_to "Editar", get_card_path(card.id), :class => "btn btn-info btn-sm margin5right", remote: true, "data-toggle" => "modal", 'data-target' => '#cardmodaledit', 'data-id' => card.id %>

					<div class="modal" id="cardmodaledit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/card/index.html.erb
<h1>Card#index</h1>
<div class="width: 100%;height:100%">
	<%= @cards.each do |card|%>
		<%= card.title %>
	<% end %>
</div>

app/views/card/modal.js.erb
$("#cardmodal").html("<%= j render 'card/modal'%>");
$("#cardmodal").show();

app/views/card/modaledit.js.erb
$("#cardmodaledit").html("<%= j render 'card/modaledit'%>");
$("#cardmodaledit").show();

app/views/card/modalshow.js.erb
$("#cardmodalshow").html("<%= j render 'card/modalshow'%>");
$("#cardmodalshow").show();

app/views/column/_form.html.erb
<div class="form-inline margin5left">
	<%= simple_form_for :column, url: create_column_path(), wrapper: :inline_form do |form| %>
		<p>Criar nova etapa: <%= form.input_field :name %> <%= form.submit "Salvar", :class => "btn btn-info btn-sm margin5right" %></p>
		
	<% end %>	
</div>

app/views/column/_modal.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Editar Etapa</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
	    <%= simple_form_for @column, url: column_edit_name_path(), wrapper: :inline_form do |form| %>
				<p>Nome: <%= form.input_field :name %> <%= form.submit "Salvar" %></p>
			<% end %>
    </div>
  </div>
</div>

app/views/column/_show.html.erb
<div class="wrapper">
	<div class="wrapper_child" data-controller="column">
		<% @columns.order(position: :asc).each do |column|%>
			<div class="tab" data-id="<%= column.id %>"  data-drag-url="/columns/:id/move">
				<div class="background" style="width: 100%; display: table;">
				    <div style="display: table-row">
						<div class="inline" style="vertical-align: middle;display: table-cell;max-width: 100px;">
							<p class="ellipsis"><%= column.name %></p>
						</div>
						<div class="inline alignright" style="margin-right: 5px">
							<%= link_to "Editar", get_column_path(column.id), :class => "btn btn-info btn-sm margin5right", remote: true, "data-toggle" => "modal", 'data-target' => '#exampleModal3', 'data-id' => column.id %>
							<div class="modal" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>

							<%= button_to("Excluir", delete_column_path(column), :method => :delete, :class => 'btn btn-info btn-sm margin5right') %>

							<%= link_to "+", get_column_card_path(column.id), :class => "btn btn-info btn-sm", remote: true, "data-toggle" => "modal", 'data-target' => '#cardmodal', 'data-id' => column.id %>
					      	<div class="modal" id="cardmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
						</div>
				    </div>
				</div>
				<div>
				<%= render 'card/show', cards: column.cards, columnid: column.id %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/column/modal.js.erb
$("#exampleModal3").html("<%= j render 'column/modal'%>");
$("#exampleModal3").show();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projtrello</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>